### ISSUE TITLE
Exclude 2.0x and 3.0x folders

### ISSUE THREAD

**Issue by 51v4** [yasfdany/flutter-asset-syncronation#1]
First of all thank you so much for creating this plugin, Its awesome <3
The plugin is not compatible with resolution-aware assets as mentioned in flutter docs [here](https://docs.flutter.dev/development/ui/assets-and-images#resolution-aware)

It would be better to add an option to exclude folders or files in settings. Before previous update it was fine because you can exclude folders by adjusting comment tag position in pubspec.yaml file

**Comment by yasfdany** [comment]
Hi @51v4 Thank you for using my plugin, I will do the research first

**Comment by yasfdany** [comment]
Hi, @51v4 I added the feature to ignore sub folders for the resolution-aware purpose, please update your plugin to the newest version 1.0.3

[31c3ccf](https://github.com/yasfdany/flutter-asset-syncronation/commit/31c3ccf2861019bbf28e403afe3bfeda9aa0aaa7)
